package com.artisan_market_place.enums;

public enum ProductCatogeryEnums {
ELECTRONICS, FASHION, HOME_APPLIANCES, BEAUTY, SPORTS, TOYS, BOOKS, AUTOMOTIVE, HEALTH, GROCERIES, PET_SUPPLIES, JEWELRY, FURNITURE, MUSIC, GARDENING, HANDMADE, ART, BABY_PRODUCTS, OFFICE_SUPPLIES, INDUSTRIAL_EQUIPMENT, MEDICAL_SUPPLIES, OUTDOOR_GEAR, SMARTPHONES, COMPUTERS, SOFTWARE, VIDEO_GAMES, FOOTWEAR, WATCHES, BAGS_AND_ACCESSORIES, FITNESS_EQUIPMENT, TRAVEL_ACCESSORIES, MUSICAL_INSTRUMENTS, HOME_DECOR, LIGHTING, KITCHEN_APPLIANCES, MOTORCYCLES_AND_ACCESSORIES, DRONES, CAMERAS, AUDIO_DEVICES, DIY_TOOLS, ECO_FRIENDLY_PRODUCTS
}
