spring.profiles.active: local
spring.jackson.time-zone: America/Los_Angeles
# HTTP Server
server:
   port: 8080
   compression.enabled: true
   tomcat.max-http-post-size:   10485760
   tomcat.max-max-swallow-size: 10485760

# log level entries
logging:
   level:
      org.hibernate: INFO
      org.apache.coyote.http11.Http11InputBuffer: DEBUG
      org.springframework.security: DEBUG
      com.artisan_market_place: DEBUG


# mysql connector details
spring:
   datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost/artisan_market_place
      driver-class-name: com.mysql.cj.jdbc.Driver

   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            ddl-auto: none
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
      database: mysql

jwt:
   secret: aqIEd34DuxRYO9J6hIjPMhu3JIFGY4YAgsp5PkRw+JzW7fQEnOy130YxvailLT1hmdTEKx/WF94nGDDVkDJXXw==
   days: 1
   days-ms: 86400000

springdoc:
   api-docs:
      enabled: true
   swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha



